#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os

os.chdir('d:\\UpgrowPlan\\upgrowplan_new')

with open('app\\[locale]\\page.en.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

translations = {
    'Реальный мир не работает по шаблонам. Ваш план тоже не должен.': 'Stop guessing. Start winning.',
    'Мы вылечили ИИ от галлюцинаций. Upgrowplan использует данные рынка и конкурентов, моделирует ваших клиентов и проверяет качество документа агентом-скептиком, чтобы создать план, который выдержит встречу с реальностью, а не просто красиво выглядит на бумаге.': 'The only platform where AI agents test your business on live data. We use Retrieval-Augmented Generation (RAG) to find real market prices, competitor insights, and regulatory changes for your specific location—not generic templates.',
    'Попробовать бесплатно': 'Try for free',
    'Поговорить с экспертом': 'Talk to an expert',
    'запущенных проектов': 'projects launched',
    'экспертизы': 'expertise',
    'стандарты моделей': 'industry standards',
    'Как ИИ-агенты Upgrowplan создают и проверяют планы на живых данных.': 'How Upgrowplan AI agents build and verify your plan using live data.',
    'Не просто генерация текста, а пошаговая валидация каждого факта.': 'Not just text generation, but step-by-step validation of every fact.',
    'Попробовать валидацию сейчас': 'Try validation now',
    'Live Валидация...': 'Live Validation...',
    'Забудьте о галлюцинациях ИИ. Каждая цифра в вашем плане имеет автора.': 'Forget AI hallucinations. Every number in your plan has an author.',
    'Прямые ссылки на официальные отчеты, налоговые кодексы и рыночную аналитику 2026 года.': 'Direct links to official reports, tax codes, and market analytics (2026).',
    'Что это значит для вас': 'What this means for you',
    'Мы используем RAG (Retrieval-Augmented Generation). ИИ сначала находит актуальные документы, читает их, и только затем пишет ваш план.': 'We use RAG (Retrieval-Augmented Generation). AI first retrieves real documents from live sources, reads them, and only then writes your plan.',
    'Результат: 0% выдумок, 100% верифицируемость.': 'Result: 0% fiction, 100% verifiable.',
    'Market & Financial Snapshot': 'Market & Financial Snapshot',
    'Министерство финансов Израиля, 2026': 'Ministry of Finance Israel, 2026',
    'Ставка НДС (Израиль, 2026):': 'VAT rate (Israel, 2026):',
    'Statista Market Outlook, 2026': 'Statista Market Outlook, 2026',
    'Объем рынка (coffee subscriptions):': 'Market size (coffee subscriptions):',
    'Рост YoY:': 'Growth rate YoY:',
    'Google Maps + Reviews Index, 2026': 'Google Maps + Reviews Index, 2026',
    'Единственный ИИ, который не боится сказать вам «нет».': 'The only AI that isn\'t afraid to tell you "no".',
    'Ваш Агент-Скептик проверит идею на прочность, найдет скрытые расходы и укажет на перенасыщенный рынок.': 'Your personal Skeptic Agent stress-tests the idea, finds hidden costs, and flags overcrowded markets.',
    'Мы готовим вас к худшему сценарию, чтобы вы были готовы к лучшему.': 'We prepare you for the worst-case scenario so you are ready for the best.',
    'Показатель доверия': 'Confidence Score',
    'Не гадайте. Спросите тех, кто действительно купит.': 'Don\'t guess. Ask those who will actually buy.',
    'Забудьте о «слепой вере». Upgrowplan создает цифровую копию вашей аудитории в нужном районе и позволяет моментально проверить любую бизнес‑гипотезу.': 'Your ideas are tested by virtual focus groups built on real demographic and behavioral data from your region.',
    'Петр Петрович': 'Peter',
    'Пожилой житель': 'Resident',
    '30–40k руб/мес': '$400–520/mo',
    'Цена/Качество': 'Price/Quality',
    'Тишина': 'Quiet',
    'Доверие': 'Trust',
    'Как раньше': 'Traditional',
    'Основано на 620 локальных отзывах': 'Based on 620 local reviews',
    'Крафтовое пиво на районе': 'Craft Beer Bar',
    'Добрый день, Петр Петрович. Планируем открыть крафтовый пивбар в вашем доме. Цены — премиум, атмосфера — тихий лофт. Как вам идея? 🍻': 'Peter, good afternoon. We\'re planning to open a craft beer pub in your building. Premium prices, quiet loft atmosphere. What do you think? 🍻',
    'Лофт? Премиум? В нашем доме уже есть разливное за 80 рублей. Я туда не хожу, шумно и контингент... А крафт за 300? Это кто пить будет, молодёжь ваша? 👴🏻': 'Loft? Premium? We already have draft beer for $1 nearby. I don\'t go there—it\'s noisy and the crowd... Craft for $5? Who\'s going to drink that? 👴🏻',
    'Мы делаем упор на тишину и культуру пития. Никакого шума после 22:00.': 'We focus on quiet atmosphere and beer culture. No noise after 10:00 PM.',
    'Тишина после 22:00? До этого вы все так обещаете. А потом будут орать под окнами. И вообще, пиво за 300... я лучше дочке на подарок добавлю. Не пойду я к вам. 😕': 'No noise after 10? Everyone promises that at first. Then people are yelling under the windows. And beer for $5... I\'d rather give my daughter money for a gift. Not coming. 😕',
    '[RAG Validation]: Гипотеза не подтверждена. Низкий интерес целевой аудитории (пенсионеры) из-за цены и страха шума. Рекомендуем пересмотреть район.': '[RAG Validation]: Hypothesis NOT validated. Low interest from target audience (seniors) due to price and noise fears. Recommend reconsidering location.',
    'Оксана': 'Oksana',
    'Офисный профессионал': 'Office Professional',
    '120–150k руб/мес': '$120–150k/mo',
    'Эстетика': 'Aesthetics',
    'Время': 'Time',
    'Статус': 'Status',
    'Технологии': 'Technology',
    'Основано на 1.1k офисных опросах': 'Based on 1.1k office surveys',
    'Семейная кондитерская у офиса': 'Family Bakery Near Office',
    'Оксана, привет. Открываем семейную кондитерскую рядом с вашим офисом. Детские праздники, ростовые куклы, торты под заказ. Будете заходить? 🍰': 'Oksana, hello. We\'re opening a family bakery near your office. Kids\' parties, character mascots, custom cakes. Would you visit? 🍰',
    'Рядом с офисом — это хорошо. Но «семейная» и «ростовые куклы»? Это значит, что там постоянно будет шумно и много детей. А я после работы хочу тишины и красивый кофе... ☕️✨': 'Near office is good. But "family" and "mascots"? That means constant noise and kids everywhere. After work I want silence and nice coffee... ☕️✨',
    'У нас будет отдельная зона для тихих встреч. И очень эстетичный интерьер.': 'We have a quiet zone for adult meetings. Very aesthetic interior.',
    'Отдельная зона? Если торты вкусные, я может и зайду один раз на пробу. Но куклы... У меня нет детей. Для свидания я выберу другое место, а для кофе — вашу эстетику может заглушить плач. 50/50. 😐': 'Quiet zone? If the cakes are good, maybe I\'ll stop by once for a taste. But mascots... I don\'t have kids. For a date I\'ll pick somewhere else. For coffee your aesthetic might get drowned out by kids crying. 50/50. 😐',
    '[RAG Validation]: Гипотеза подтверждена на 50%. Интерес есть к продукту (эстетика/кофе), но концепция «семейной» кондитерской отпугивает платежеспособную аудиторию без детей.': '[RAG Validation]: Hypothesis PARTIALLY validated. Interest in product (aesthetics/coffee) confirmed, but "family bakery" concept repels affluent childless audience.',
    'Мария': 'Maria',
    'Хозяйка пекарни': 'Bakery Owner',
    '200–250k руб/мес': '$200–250k/mo',
    'Юнит-экономика': 'Unit Economics',
    'Операционка': 'Operations',
    'Качество': 'Quality',
    'Конкуренция': 'Competition',
    'Основано на 1.2k HoReCa отзывах': 'Based on 1.2k HoReCa reviews',
    'Шеринг инструментов «СтройСам»': 'Tool-Sharing Service \'BuildYourself\'',
    'Мария, добрый день. Планируем сервис шеринга дорогих инструментов: перфораторы, тепловизоры. Как вы, как предприниматель, оцениваете идею? 🛠': 'Maria, good day. We\'re launching a tool-sharing service for expensive equipment: drills, thermal cameras. As an entrepreneur, what\'s your take? 🛠',
    'Хм. Идея интересная. Я сама в пекарню миксер за 150k покупала. Но как вы решите вопрос с залогом и, главное, с логистикой и ремонтом? 🤯': 'Interesting idea. I bought a mixer for my bakery for $15k. But how will you handle deposits and especially logistics and repairs? 🤯',
    'Залог — через блокировку на карте. Ремонт — страховка. Доставка — курьеры.': 'Deposit via card hold. Repairs covered by insurance. Delivery via couriers.',
    'Курьеры? Это же дорого. А если перфоратор сломали «случайно»? Кто это будет проверять? Если цена аренды будет 1000 рублей, вы не покроете операционные расходы. Я бы не рискнула, слишком сложная логистика. 📈📉': 'Couriers? That\'s expensive. What if someone breaks a drill "accidentally"? Who inspects it? If rental is $100, you won\'t cover operational costs. I wouldn\'t risk it—too complex logistics. 📈📉',
    '[RAG Validation]: Гипотеза не подтверждена. Высокие операционные расходы и риски (логистика/ремонт) убивают юнит-экономику для этой целевой аудитории.': '[RAG Validation]: Hypothesis NOT validated. High operational costs and risks (logistics/repairs) kill unit economics for this audience.',
    'Никита': 'Nikita',
    'Студент-мечтатель': 'Student Dreamer',
    '15–20k руб/мес': '$15–20k/mo',
    'Тренды': 'Trends',
    'Хайп': 'Hype',
    'Экология': 'Ecology',
    'Сообщество': 'Community',
    'Основано на 900 интервью со студентами': 'Based on 900 student interviews',
    'Школа каллиграфии онлайн': 'Online Calligraphy School',
    'Никита, привет. Тестируем идею онлайн-школы каллиграфии. Это успокаивает, развивает мозг и сейчас в тренде на экологичность. Запишешься на курс? ✍️': 'Nikita, hey. Testing online calligraphy school idea. It\'s relaxing, develops the brain, and trending in eco-conscious circles. Sign up for the course? ✍️',
    'Вау. Онлайн-школа... но медленное письмо? Я в универе лекции не пишу, все в Notion. У меня времени нет на «медленно». Это какой-то хайп для бумеров. 😴': 'Wow. Online school... but slow handwriting? I don\'t write notes in uni—everything goes to Notion. I don\'t have time for "carefully." That\'s some boomer trend. 😴',
    'Это позволяет разгрузить мозг от гаджетов. Сообщество, оффлайн встречи.': 'It helps unplug from gadgets. Community, offline meetups.',
    'Оффлайн встречи — это круче. Но каллиграфия? Я лучше пойду на курсы по AI или хотя бы гончарному делу. Там продукт можно потрогать. А буквы писать... не, это не для меня, сорри. 🤷‍♂️': 'Offline meetups—that\'s better. But calligraphy? I\'d rather take AI or pottery courses. At least you can touch the product. Writing letters... nah, not for me. 🤷‍♂️',
    '[RAG Validation]: Гипотеза не подтверждена. Целевая аудитория (студенты) ценит скорость и практичный результат, а не «медленные» хайпы. Тренд экологичности не работает в этом контексте.': '[RAG Validation]: Hypothesis NOT validated. Target audience (students) values speed and practical output, not "slow" trends. Eco angle doesn\'t convert in this context.',
    'Виктор Борисович': 'Victor Borisovich',
    'Директор': 'Director',
    '400k+ руб/мес': '$400k+ /mo',
    'Риски': 'Risks',
    'Масштаб': 'Scale',
    'Финмодель': 'Financial Model',
    'Стратегия': 'Strategy',
    'Основано на 420 интервью с директорами': 'Based on 420 director interviews',
    'Франшиза автомоек «Антигрязь»': 'Franchise: Automatic Car Washes',
    'Виктор Борисович, добрый день. Рассматриваем покупку франшизы автоматических моек. Качество среднее, но скорость (3 минуты) и низкая маржа. Что скажете? 🚗💨': 'Victor Borisovich, good day. We\'re considering buying a franchise for self-service car washes. Medium quality but speed (3 minutes) and low margins. Your thoughts? 🚗💨',
    'Скорость — это отлично, москвичи это ценят. Низкая маржа? Это сколько? Если чистая прибыль 5% — это не бизнес, это благотворительность. Покажите финмодель. 📊🧐': 'Speed is great, Muscovites value it. Low margin? How low? If net profit is 5%—that\'s not a business, that\'s charity. Show me the financial model. 📊🧐',
    'Вот скриншот нашей финансовой модели. Капекс высокий, но окупаемость — 18 месяцев за счет оборота.': 'Here\'s our financial model screenshot. CapEx is high but payback—18 months thanks to throughput.',
    'Окупаемость 18 месяцев при капексе 10 млн? Это при загрузке 24/7? В Москве рынок перенасыщен, конкуренты (у которых качество выше) задушат вас ценой. Я бы не стал вкладываться, риск масштабируемости слишком высок. Не верю я в 3 минуты без потери качества. 📉❌': 'Payback in 18 months with $10M CapEx? Only at 24/7 capacity? Moscow\'s market is saturated. Competitors with better quality will undercut. I don\'t see 3-minute quality without compromise. Risk of scalability is too high. Won\'t invest. 📉❌',
    '[RAG Validation]: Гипотеза не подтверждена. Опытный инвестор считает финансовую модель слишком оптимистичной, а рыночную конкуренцию в Москве — фатальной.': '[RAG Validation]: Hypothesis NOT validated. Experienced investor finds financial model too optimistic, market competition fatal.',
    'Елена': 'Elena',
    'Домохозяйка': 'Homemaker',
    '70–90k руб/мес': '$70–90k/mo',
    'Удобство': 'Convenience',
    'Дети': 'Children',
    'Лояльность': 'Loyalty',
    'Основано на 1.5k домашних опросах': 'Based on 1.5k household surveys',
    'Подписка на уборку «Чистый Понедельник»': 'Cleaning Subscription \'Clean Monday\'',
    'Елена, здравствуйте. Открываем сервис регулярной уборки квартир по подписке. 2 раза в месяц, фиксированная цена, те же клинеры. Будете пользоваться? 🧹✨': 'Elena, hi. We\'re launching a regular apartment cleaning subscription service. Twice a month, fixed price, same cleaners. Would you use it? 🧹✨',
    'Подписка на уборку? Это было бы супер. У меня двое детей, и к выходным квартира превращается в поле битвы. Но мне важен один клинер, чтобы я не боялась оставить его дома. 🥰': 'Regular cleaning subscription? That would be amazing. I have two kids and by Friday the place is a battlefield. But I need one cleaner I trust—I won\'t leave a stranger alone. 🥰',
    'Да, мы гарантируем, что к вам будет ходить одна и та же клинер, обученная по нашему стандарту. И залог не нужен.': 'Yes, we guarantee the same cleaner comes to you, trained to our standards. No deposit required.',
    'Отлично. Цена 5000 рублей за две уборки в месяц — это приемлемо. Если клинер действительно хорошая, я сэкономлю себе 8 часов жизни. Я запишусь! И подругам посоветую. ❤️🗓': 'Perfect. $500 for two cleanings a month is acceptable. If the cleaner is really good, I save 8 hours of my life. I\'m in! And I\'ll tell my friends. ❤️🗓',
    '[RAG Validation]: Гипотеза подтверждена. Сервис закрывает боли целевой аудитории (домохозяйки) по времени и доверию при приемлемой цене. Высокий виральный потенциал.': '[RAG Validation]: Hypothesis VALIDATED. Service closes target audience pain (time, trust) at acceptable price. High viral potential.',
}

for rus, eng in translations.items():
    content = content.replace(rus, eng)

with open('app\\[locale]\\page.en.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print('Translation complete!')
