"use client";

import { useState } from "react";
import { Card, Badge, Row, Col, Button, Accordion } from "react-bootstrap";
import {
  FiDownload,
  FiCheck,
  FiAlertCircle,
  FiTrendingUp,
  FiUsers,
  FiBarChart2,
  FiBookmark,
} from "react-icons/fi";

interface Recommendation {
  priority: string;
  category: string;
  recommendation: string;
  rationale: string;
}

interface ReportData {
  success: boolean;
  report_id: number;
  research_id: number;
  executive_summary: string;
  persona_insights: any;
  survey_results: any;
  price_analysis: any;
  motivation_analysis: any;
  readiness_analysis: any;
  recommendations: Recommendation[];
  created_at: string;
  message: string;
}

interface ReportDisplayProps {
  report: ReportData | null;
  isLoading: boolean;
  onExport?: (format: string) => void;
}

export default function ReportDisplay({
  report,
  isLoading,
  onExport,
}: ReportDisplayProps) {
  const [expandedRecommendation, setExpandedRecommendation] = useState<
    number | null
  >(null);

  const handleExportPDF = () => {
    if (!report) return;

    // Create a simple HTML representation
    const htmlContent = `
      <html>
        <head>
          <meta charset="UTF-8">
          <style>
            body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
            h1 { color: #1e6078; border-bottom: 2px solid #1e6078; padding-bottom: 10px; }
            h2 { color: #2d7a9a; margin-top: 30px; }
            .summary { background: #f8f9fa; padding: 15px; border-left: 4px solid #1e6078; margin: 15px 0; }
            .recommendation { background: #fff3cd; padding: 10px; margin: 10px 0; border-radius: 4px; }
          </style>
        </head>
        <body>
          <h1>Marketing Research Report</h1>
          <p>Generated: ${new Date(report.created_at).toLocaleString(
            "ru-RU"
          )}</p>
          
          <h2>Executive Summary</h2>
          <div class="summary">${report.executive_summary}</div>
          
          <h2>Key Recommendations</h2>
          ${
            report.recommendations
              ?.map(
                (r: any) =>
                  `<div class="recommendation"><strong>${r}</strong></div>`
              )
              .join("") || ""
          }
          
          <h2>Survey Results</h2>
          <pre>${JSON.stringify(report.survey_results, null, 2)}</pre>
        </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: "application/pdf" });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `report_${report.research_id}_${
      new Date().toISOString().split("T")[0]
    }.pdf`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);

    onExport?.("pdf");
  };

  const handleExportDOCX = async () => {
    if (!report) return;

    try {
      // For DOCX, we'll create a simple text-based export
      // In production, you'd use a library like docx or similar
      const docContent = `
MARKETING RESEARCH REPORT
Generated: ${new Date(report.created_at).toLocaleString("ru-RU")}
Research ID: ${report.research_id}

═══════════════════════════════════════════════════════════

EXECUTIVE SUMMARY
${report.executive_summary}

═══════════════════════════════════════════════════════════

KEY RECOMMENDATIONS
${
  report.recommendations
    ?.map((r: any, i: number) => `${i + 1}. ${r}`)
    .join("\n") || "No recommendations"
}

═══════════════════════════════════════════════════════════

SURVEY RESULTS
${JSON.stringify(report.survey_results, null, 2)}

═══════════════════════════════════════════════════════════

Generated by Synth Focus Lab
`;

      const blob = new Blob([docContent], {
        type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `report_${report.research_id}_${
        new Date().toISOString().split("T")[0]
      }.docx`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      onExport?.("docx");
    } catch (error) {
      console.error("Error exporting DOCX:", error);
    }
  };

  if (isLoading) {
    return (
      <Card className="shadow-sm mb-4">
        <Card.Body className="text-center py-5">
          <div className="spinner-border text-primary mb-2" role="status">
            <span className="visually-hidden">Generating report...</span>
          </div>
          <p className="text-muted">Generating market research report...</p>
        </Card.Body>
      </Card>
    );
  }

  if (!report || !report.success) {
    return (
      <Card className="shadow-sm mb-4 border-danger">
        <Card.Body>
          <div className="d-flex align-items-center">
            <FiAlertCircle className="text-danger me-3" size={24} />
            <div>
              <h6 className="mb-0 text-danger">Report Not Available</h6>
              <small className="text-muted">
                {report?.message || "Failed to load report"}
              </small>
            </div>
          </div>
        </Card.Body>
      </Card>
    );
  }

  const getPriorityBadge = (priority: string) => {
    const variants: { [key: string]: string } = {
      HIGH: "danger",
      MEDIUM: "warning",
      LOW: "secondary",
    };
    return <Badge bg={variants[priority] || "secondary"}>{priority}</Badge>;
  };

  return (
    <div className="report-display">
      {/* Header */}
      <Card
        className="shadow-sm mb-4 border-0"
        style={{ backgroundColor: "#f8f9fa" }}
      >
        <Card.Body>
          <div className="d-flex justify-content-between align-items-start mb-3">
            <div>
              <h4 className="mb-2" style={{ color: "#1e6078" }}>
                Market Research Report
              </h4>
              <small className="text-muted">
                Report ID: {report.report_id} | Generated:{" "}
                {new Date(report.created_at).toLocaleDateString("ru-RU")}
              </small>
            </div>
            {onExport && (
              <div className="btn-group" role="group">
                <Button
                  variant="outline-primary"
                  size="sm"
                  onClick={handleExportPDF}
                  title="Export as PDF"
                >
                  <FiDownload className="me-1" /> PDF
                </Button>
                <Button
                  variant="outline-primary"
                  size="sm"
                  onClick={handleExportDOCX}
                  title="Export as DOCX"
                >
                  <FiDownload className="me-1" /> DOCX
                </Button>
              </div>
            )}
          </div>
        </Card.Body>
      </Card>

      {/* Executive Summary */}
      <Card className="shadow-sm mb-4 border-0">
        <Card.Header className="bg-light d-flex align-items-center">
          <FiBookmark className="me-2 text-primary" />
          <strong>Executive Summary</strong>
        </Card.Header>
        <Card.Body>
          <p
            className="text-justify"
            style={{ whiteSpace: "pre-wrap", lineHeight: "1.6" }}
          >
            {report.executive_summary}
          </p>
        </Card.Body>
      </Card>

      {/* Personas */}
      {report.persona_insights && (
        <Card className="shadow-sm mb-4 border-0">
          <Card.Header className="bg-light d-flex align-items-center">
            <FiUsers className="me-2 text-primary" />
            <strong>Target Personas</strong>
          </Card.Header>
          <Card.Body>
            <Row className="mb-3">
              <Col md={6}>
                <div className="p-3 border rounded">
                  <h6 className="mb-2">Total Personas Identified</h6>
                  <h3 style={{ color: "#0785f6" }}>
                    {report.persona_insights.total_personas || 0}
                  </h3>
                </div>
              </Col>
              <Col md={6}>
                <div className="p-3 border rounded">
                  <h6 className="mb-2">Segments</h6>
                  <div>
                    {Object.keys(report.persona_insights.segments || {}).map(
                      (segment) => (
                        <Badge key={segment} bg="info" className="me-2 mb-2">
                          {segment}
                        </Badge>
                      )
                    )}
                  </div>
                </div>
              </Col>
            </Row>

            <h6 className="mt-3 mb-2">Common Pain Points</h6>
            <div className="mb-3">
              {report.persona_insights.common_pains?.map(
                (pain: string, idx: number) => (
                  <div key={idx} className="mb-2">
                    <small>
                      <span className="badge bg-warning me-2">{idx + 1}</span>
                      {pain}
                    </small>
                  </div>
                )
              )}
            </div>

            <h6 className="mb-2">Common Objections</h6>
            <div>
              {report.persona_insights.common_objections?.map(
                (obj: string, idx: number) => (
                  <div key={idx} className="mb-2">
                    <small>
                      <FiAlertCircle
                        className="me-2 text-warning"
                        style={{ display: "inline" }}
                      />
                      {obj}
                    </small>
                  </div>
                )
              )}
            </div>
          </Card.Body>
        </Card>
      )}

      {/* Survey Results by Category */}
      <Card className="shadow-sm mb-4 border-0">
        <Card.Header className="bg-light d-flex align-items-center">
          <FiBarChart2 className="me-2 text-primary" />
          <strong>Survey Results Analysis</strong>
        </Card.Header>
        <Card.Body>
          <Row>
            {/* Price Sensitivity */}
            {report.price_analysis && (
              <Col md={6} className="mb-3">
                <div className="p-3 border rounded h-100">
                  <h6 className="mb-2 text-primary">💰 Price Sensitivity</h6>
                  <div className="mb-2">
                    <small className="text-muted">Average Score</small>
                    <h5 style={{ color: "#0785f6" }}>
                      {report.price_analysis.insights?.[0] || "N/A"}
                    </h5>
                  </div>
                  <small className="text-muted">Key Insights:</small>
                  <ul className="small mb-0 mt-2">
                    {report.price_analysis.insights
                      ?.slice(1, 3)
                      .map((insight: string, idx: number) => (
                        <li key={idx}>{insight}</li>
                      ))}
                  </ul>
                </div>
              </Col>
            )}

            {/* Motivation */}
            {report.motivation_analysis && (
              <Col md={6} className="mb-3">
                <div className="p-3 border rounded h-100">
                  <h6 className="mb-2 text-primary">
                    🎯 Motivation & Benefits
                  </h6>
                  <div className="mb-2">
                    <small className="text-muted">Average Score</small>
                    <h5 style={{ color: "#0785f6" }}>
                      {report.motivation_analysis.insights?.[0] || "N/A"}
                    </h5>
                  </div>
                  <small className="text-muted">Key Insights:</small>
                  <ul className="small mb-0 mt-2">
                    {report.motivation_analysis.insights
                      ?.slice(1, 3)
                      .map((insight: string, idx: number) => (
                        <li key={idx}>{insight}</li>
                      ))}
                  </ul>
                </div>
              </Col>
            )}
          </Row>

          {/* Readiness to Act */}
          {report.readiness_analysis && (
            <Row>
              <Col md={12} className="mb-3">
                <div className="p-3 border rounded">
                  <h6 className="mb-2 text-primary">✅ Readiness to Act</h6>
                  <small className="text-muted">Key Insights:</small>
                  <ul className="small mb-0 mt-2">
                    {report.readiness_analysis.insights
                      ?.slice(0, 4)
                      .map((insight: string, idx: number) => (
                        <li key={idx}>{insight}</li>
                      ))}
                  </ul>
                </div>
              </Col>
            </Row>
          )}
        </Card.Body>
      </Card>

      {/* Recommendations */}
      {report.recommendations && report.recommendations.length > 0 && (
        <Card className="shadow-sm mb-4 border-0">
          <Card.Header className="bg-light d-flex align-items-center">
            <FiTrendingUp className="me-2 text-primary" />
            <strong>Strategic Recommendations</strong>
          </Card.Header>
          <Card.Body>
            <Accordion defaultActiveKey={["0"]} alwaysOpen>
              {report.recommendations.map((rec, idx) => (
                <Accordion.Item eventKey={idx.toString()} key={idx}>
                  <Accordion.Header>
                    <div className="d-flex align-items-center w-100">
                      {getPriorityBadge(rec.priority)}
                      <span className="ms-2 fw-bold">{rec.recommendation}</span>
                      <small className="ms-auto text-muted me-3">
                        {rec.category}
                      </small>
                    </div>
                  </Accordion.Header>
                  <Accordion.Body>
                    <div>
                      <h6 className="mb-2">Rationale</h6>
                      <p className="text-muted">{rec.rationale}</p>
                      <div className="d-flex gap-2 mt-3">
                        <Badge bg="light" text="dark">
                          {rec.category}
                        </Badge>
                        <Badge bg="light" text="dark">
                          Priority: {rec.priority}
                        </Badge>
                      </div>
                    </div>
                  </Accordion.Body>
                </Accordion.Item>
              ))}
            </Accordion>
          </Card.Body>
        </Card>
      )}

      {/* Summary Stats */}
      <Row className="mb-4">
        <Col md={4}>
          <Card className="text-center shadow-sm border-0">
            <Card.Body>
              <FiCheck className="text-success mb-2" size={28} />
              <h6>Recommendations</h6>
              <h4 style={{ color: "#0785f6" }}>
                {report.recommendations?.length || 0}
              </h4>
            </Card.Body>
          </Card>
        </Col>
        <Col md={4}>
          <Card className="text-center shadow-sm border-0">
            <Card.Body>
              <FiUsers className="text-info mb-2" size={28} />
              <h6>Personas</h6>
              <h4 style={{ color: "#0785f6" }}>
                {report.persona_insights?.total_personas || 0}
              </h4>
            </Card.Body>
          </Card>
        </Col>
        <Col md={4}>
          <Card className="text-center shadow-sm border-0">
            <Card.Body>
              <FiBarChart2 className="text-warning mb-2" size={28} />
              <h6>Analysis Depth</h6>
              <h4 style={{ color: "#0785f6" }}>Deep</h4>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </div>
  );
}
