export const LABELS = {
  pageTitle: "Social Plan Master",
  pageDescription: "AI synthesis of social impact strategy, business plan and market analysis",
  formTitle: "Synthesis Parameters",
  basicInfo: "Basic Information",
  businessIdeaLabel: "Business Idea",
  businessIdeaPlaceholder: "Description of your business idea...",
  targetMarketLabel: "Target Market",
  targetMarketPlaceholder: "Description of target market and audience...",
  businessCategoryLabel: "Business Category",
  businessCategoryPlaceholder: "E.g.: specialty coffee, e-commerce, saas",
  regionLabel: "Region",
  regionPlaceholder: "E.g.: Kaliningrad, Russia",
  businessTypeTitle: "Business Type",
  businessTypePlaceholder: "B2B, B2C, B2B2C, etc.",
  productTypeTitle: "Product Type",
  productTypePlaceholder: "Select product categories...",
  initialInvestmentLabel: "Initial Investment",
  initialInvestmentPlaceholder: "E.g.: 1000000",
  plannedHeadcountLabel: "Planned Team Size",
  plannedHeadcountPlaceholder: "Number of employees...",
  hasSocialImpactLabel: "Social / Environmental Impact",
  submitButton: "Start Synthesis"
};
